# Generated by Django 4.2.6 on 2023-10-31 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathurst', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lectures',
            new_name='Capteurs',
        ),
    ]
