# Generated by Django 4.2.6 on 2023-10-31 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bathurst', '0002_rename_lectures_capteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteurs',
            name='Date_envoi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capteurs',
            name='Heure_envoi',
            field=models.TimeField(auto_now=True),
        ),
    ]
