# Generated by Django 4.2.6 on 2023-10-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathurst', '0003_capteurs_date_envoi_capteurs_heure_envoi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capteurs',
            old_name='Date_envoi',
            new_name='DatEnvoi',
        ),
        migrations.RenameField(
            model_name='capteurs',
            old_name='Heure_envoi',
            new_name='HeurEnvoi',
        ),
    ]
